### ISSUE TITLE
need windows prebuilt binary for 1.3.0

### ISSUE THREAD

**Issue by maxogden** [Level/leveldown#202]
if anyone has a windows machine and can build a release for https://github.com/Level/leveldown/releases/tag/v1.3.0 that would be awesome! 

also, do we have any docs on what commands to run to do a 'prebuilt binary build'? could it be boiled down to a npm script?

**Comment by rvagg** [comment]
Instructions would help, I could do the compile but against which version of Node? Multiple versions I'm guessing, do we have a list of `NODE_MODULE_VERSION`s that we are supporting? Also, what needs to be bundled up for distribution? The entire `build` directory or just `build/leveldown.node`?

**Comment by No9** [comment]
Hi @maxogden 
I packaged one of these the other day for node v0.12.7  https://drive.google.com/file/d/0B1Sqmq8yhAUVTlpyUXlXUFI1NnM/view?usp=sharing 
Please @ me here if your want iojs or other runtime. 

@ralphtheninja Can I do anything as part of your pre-gyp stuff to help this as it's the second time we have run into this in a week.

**Comment by ralphtheninja** [comment]
This has slowed down lately because I've been busy with other things. Check out the `node-pre-gyp-and-travis` branch (rebased it onto latest master) to see current progress. It assumes `node-pre-gyp` is used to publish the binaries, but we can obviously change that to something else, and we probably should.

I wanted to use `travis` to build the binaries for us, so contacted travis support and they made it possible for us to to run OSX.

Short run down:

* `.travis.yml` is setup as `language: cpp` so we can do whatever we like and not rely on the built in `nvm`
* We use a matrix so travis generates a build for each line in the matrix and for all os'es (e.g. linux and osx)
* We use `n` to install whatever version of node/iojs we want to build with
* I've updated `n` so it can install 32 bit versions of node and iojs on 64 bit systems, i.e. there's no need to build on a 32 bit system to get 32 bit binaries
* I've also added a build script in `scripts/build-all-linux-osx.sh` with the idea that this script *should* abstract the build process, if we are building on some other system than `travis`
* I've added a `Makefile`. Basically `make` builds the binaries and `make clean` should put leveldown in a clean state
* I've chosen the different versions of node/iojs based on different ABI versions

After a gazillion force pushes to travis it's sort of working right now, except for publishing the binaries. Have a look here:

https://travis-ci.org/Level/leveldown/builds/72308960

My vacation starts in a couple of days and I will have more bandwidth then. If anyone else wants to jump in and help out, feel free to do so :)

**Comment by ralphtheninja** [comment]
On a side note, I also wrote [`ghreleases`](https://github.com/ralphtheninja/ghreleases) based on @rvagg 's `gh*` modules and the idea was to use that to publish binaries directly to GitHub.

For building on windows we should probably write a windows specific build script. That script in turn should use something that can install different versions of node on windows machines but my knowledge is limited in that area.

Perhaps @No9 have an idea?

**Comment by ralphtheninja** [comment]
Oh yeah, I forgot something. If you take a look at `package.json` I added the following:

```json
  "scripts": {
    "install": "node-pre-gyp install --fallback-to-build",
    "test": "tape test/*-test.js | faucet",
    "release-major": "npm version -m '[publish binary]' major",
    "release-minor": "npm version -m '[publish binary]' minor",
    "release-patch": "npm version -m '[publish binary]' patch"
  }
```

The idea here was to use e.g. `npm run release-minor` to create create a version with `'[publish binary]'` in the commit message and have that as a seam for actually publishing the binaries.

Hope this clears up some.

**Comment by maxogden** [comment]
@ralphtheninja @No9 when you get a chance could you add a npm script called `compile` that we could run e.g.

- `npm run compile`
- it would build leveldown on the current platform using whatever node is currently installed
- it would create the correctly named `.zip` in the `build` directory (or wherever it makes sense to save it

that way theres a manual way to build that just involves running a single npm script, and we can even call that script in the higher level build automation stuff ya'll are working on. I would do this but I am not as comfortable with native build stuff

**Comment by mafintosh** [comment]
I'm gonna do some work on this today

**Comment by ralphtheninja** [comment]
@maxogden I'm closing this now since @mafintosh has done amazing work with `prebuild`!
