### ISSUE TITLE
Is it possible/reasonnable to repair the database while in use?

### ISSUE THREAD

**Issue by julien-f** [Level/leveldown#237]

**Comment by ralphtheninja** [comment]
@julien-f Why would you need to repair a db that is in use?

**Comment by julien-f** [comment]
The documentation says that this can also be used to compact the database.

Anyway my question is more: should I protect my users against repairing while the db is in use because leveldown/leveldb does not guard against it?

**Comment by ralphtheninja** [comment]
> Anyway my question is more: should I protect my users against repairing while the db is in use because leveldown/leveldb does not guard against it?

Good question. Not sure how you could guard against it though.

**Comment by No9** [comment]
@julien-f that sounds like the type of feature that @rescrv might have in https://github.com/rescrv/HyperLevelDB but he would need to confirm (of Deny)

**Comment by bookchin** [comment]
@julien-f it's been awhile, but if you are using `repair()` to trigger compaction, better use `compactRange()` instead as a database repair has other side effects and should not be performed on an open database. the [`compactRange`](https://github.com/Level/leveldown#leveldown_compactRange) method can be called on an open database.

**Comment by Leland-Kwong** [comment]
Is there a way to call `compactRange` so that we can compact everything? In particular, the keys can vary both by type and value, so I'm wondering if we can do something like `compactRange('*', '*', cb)`? 

The main use case here is to compact a database when all the data has been removed. I noticed without compaction, a good bit of `.ldb` files still remain.
