### ISSUE TITLE
Change storage backend?

### ISSUE THREAD

**Issue by tantaman** [Level/leveldown#242]
Is there a way to change the backend that leveldown uses to rocksdb instead of leveldb?  level-rocksdb seems woefully out of date and broken.

**Comment by ralphtheninja** [comment]
It doesn't have to do with `level-rocksdb` at all since it merely bundles the `levelup` and `rocksdb` modules.

The backend is in this repository on the `rocksdb` branch. What needs to be done is to make that branch play nice with the latest `nan`.

I personally don't have any experience of this work but I could try taking a look to see what it takes to make that branch compile. We should probably also consider making this into a fork of `leveldown` and use that as an upstream repo.

**Comment by gritzko** [comment]
I think, I can help you with the effort.
RocksDB seems more production-ready for server-side loads.
AFAIK, leveldb was mostly envisioned as a client-side thing.
