### ISSUE TITLE
Download prebuild for a different target platform than the one installing the package

### ISSUE THREAD

**Issue by limoragni** [Level/leveldown#243]
Is it possible to tell `prebuild` to target a different OS than the one I'm currently using? 

I'm using electron and I'm building all the releases from linux. Before I installed leveldown I was able to build for OSX and WIN. I was told that using `node-pre-gyp install --target_platform=darwin --target_arch=x64 --target={electron_version}` I could change the target platform, but you are not using node-pre-gyp anymore. 

Is there any way of download the leveldown prebuild for a target other that the current platform?

**Comment by ralphtheninja** [comment]
We're discussing it here https://github.com/mafintosh/prebuild/issues/61 .. it's sort of tricky to make it "just work" since electron might be installed globally, or locally (https://github.com/mafintosh/electron-prebuilt), which means that if you want to make `prebuild` do this automatically you would have to do it in the postinstall step.

An alternative would be to expose some arguments where you explicitly set the target. Target is also not enough since for electron you also need to specify a `dist-url` so `node-gyp` knows *where* to download the headers from.

**Comment by limoragni** [comment]
Ok, I see. So in order to use leveldown with electron you need to build against the electron runtime? Wouldn't be enough if you could download a prebuild for a particular node/os? Like `prebuild install --download --target_platform=darwin --target_arch=x64 --node_version=4.1.1` I have little experience with cross platform development since I come from a web background. But if I install leveldown on my machine using npm and having the same node version electron has, it works fine. And the other question I have is, if you build against the electron runtime you can then use it on different platforms? Sorry if this are basic questions, but I don't really know much about building stuff and cross platform development. Thanks!

**Comment by ralphtheninja** [comment]
> Ok, I see. So in order to use leveldown with electron you need to build against the electron runtime?

Correct. Since electron is a separate environment all native modules needs to be built against that environment. This has to do with what abi (application binary interface) version that environment has, which essentially depends on what kind of v8 it was based on (afaik).

> But if I install leveldown on my machine using npm and having the same node version electron has, it works fine.

The reason this works is because node and electron have the same abi version

> And the other question I have is, if you build against the electron runtime you can then use it on different platforms?

Nope. You still need to build for each platform, so I'd guess if you are developing some electron application (that uses native modules) and want to target multiple platforms, you would have to build for each platform and bundle it.

> Sorry if this are basic questions, but I don't really know much about building stuff and cross platform development.

No worries :)

@mafintosh Anything to add?

**Comment by ralphtheninja** [comment]
https://github.com/juliangruber/require-rebuild
