### ISSUE TITLE
Unable to build on aix-ppc64 or linux-s390

### ISSUE THREAD

**Issue by CurryKitten** [Level/leveldown#306]
Attempting to run tests on level & leveldown.  There's no prebuilds for aix-ppc64 or linux-s390, but there's also a failure attempting to build from source.

`gyp: Undefined variable os_include in /leveldown/deps/snappy/snappy.gy`p

Which looks to be falling over here, as an OS of AIX isn't accounted for 

```
            ['OS=="linux"',   {'os_include': 'linux'}]
          , ['OS=="mac"',     {'os_include': 'mac'}]
          , ['OS=="solaris"', {'os_include': 'solaris'}]
          , ['OS=="win"',     {'os_include': 'win32'}]
          , ['OS=="freebsd"', {'os_include': 'freebsd'}]

```

linux-s390 comes back with the error 

`#error Please implement AtomicPointer for this platform.`

Which I guess is fairly self-explanatory, although I wasn't sure how trivial this (or adding AIX as an OS - along with the associated config.h/snappy-stubs-public.h under dips/snappy) would be ?

**Comment by ralphtheninja** [comment]
> #error Please implement AtomicPointer for this platform.

I believe this error relates to the `LevelDB` code base, which would have to be fixed first since `leveldown` is just a layer on top of that. See https://github.com/google/leveldb/blob/master/port/atomic_pointer.h#L229

**Comment by vweevers** [comment]
It seems LevelDB has no intention of supporting AIX (https://github.com/google/leveldb/issues/326, https://github.com/google/leveldb/issues/61). 

If it's feasible to patch LevelDB on our side - meaning without requiring too many changes or maintenance to keep patches up to date - feel free to send us a PR for consideration.

In the mean time, because this issue is stale and there have been no upvotes, I'm closing.
