### ISSUE TITLE
Iterator.seek() not working properly

### ISSUE THREAD

**Issue by peakji** [Level/leveldown#322]
According to the docs:
> By calling seek(key), subsequent calls to next(cb) will return key/values larger or smaller than key ...

But it seems that seek can only work for the first time:

```javascript
const leveldown = require("leveldown");
const location = "./temp";
const db = leveldown(location);

db.open(function(err) {

	// Write 8 keys
	var batch = db.batch();
	for (var i = 1; i <= 8; i++)
		batch.put("0" + i, i);
	batch.write(function(err) {

		var ite = db.iterator();

		// Seek to "02"
		ite.seek("02");
		ite.next(function(err, key, val) {

			// Prints "02 2"
			console.log(key.toString(), val.toString());

			// Seek to "05"
			ite.seek("05");
			ite.next(function(err, key, val) {

				// Prints "undefined undefined" ?!
				console.log(key, val);

				// Clean up
				ite.end(function() {
					db.close(function() {
						leveldown.destroy(location, console.log);
					});
				});
			});
		});
	});
});
```

**Comment by vweevers** [comment]
This happens because `next()` reads ahead. It fills up a cache of key/value pairs, which in this case is the entire db, after which the iterator is considered to be finished. While `seek()` does clear the cache, it does not reset the finished state. That's why the second `ite.next()` here yields `undefined`, which signifies the end.

Maybe this is easy to fix, if we add `this.finished = false` after [iterator.js#L20](https://github.com/Level/leveldown/blob/master/iterator.js#L20). But I'm not 100% sure if a subsequent call to `next()` is safe in C++ land. /cc @ralphtheninja?

**Comment by peakji** [comment]
@vweevers I've checked the leveldb code and wrote some tests, I think its safe.

Setting `this.finished` to `false` and clearing `cache` will not cause any error, but only wasting some read ahead IO in edge cases, and this is not a big problem (`highWaterMark = 16 * 1024`).
