### ISSUE TITLE
Drop node 0.12

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#382]
Continuing from https://github.com/Level/leveldown/issues/380#issuecomment-325197439:

> I think dropping support for Node.js versions should be semver-major change.
>
> We might want to think of using n-api. We are currently discussing the possibility to have a "single binary to rule them all", including both 4 and 6 on Linux and Mac (not Windows).

@ralphtheninja @mcollina @juliangruber

**Comment by juliangruber** [comment]
afaik there's a port of leveldown to n-api already somewhere?

**Comment by ralphtheninja** [comment]
I don't even know what n-api is. Someone fill me in? :)

**Comment by mcollina** [comment]
n-api is https://nodejs.org/api/n-api.html. It's an ABI-stable binding across Node.js versions. By using it, we can avoid to compile one binary for every Node.js version available. n-api is a C API, and what we would use is https://github.com/nodejs/node-addon-api instead, which is a C++ wrapper. It's similar to NAN, but it will be simpler to use (now it does not have good docs) - as it's more C++ rather than relying on macros (like NAN).

Currently it's experimental, so we shouldn't really ship with it in the near future.

There is a port in https://github.com/jasongin/leveldown/tree/napi.

**Comment by ralphtheninja** [comment]
We currently can't make prebuilts for 0.12 because of this error

https://travis-ci.org/Level/leveldown/jobs/280998747

Good ole `SyntaxError: Use of const in strict mode`

**Comment by ralphtheninja** [comment]
Not sure what to "blame", if it's `node-gyp`, `request`, `hawk` or `boom`.

**Comment by ralphtheninja** [comment]
Created an issue here https://github.com/prebuild/prebuild/issues/188

**Comment by vweevers** [comment]
Let's drop 0.12 and release a major. Everyone on board? @ralphtheninja @juliangruber @mcollina

**Comment by ralphtheninja** [comment]
Lets make a new issue for node 4 and 5 when we decide to drop those.
