### ISSUE TITLE
Release new major v5.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#550]
Just making an issue for this for referencing other ongoing work. We will release some `rc`'s first and once we have released `v5.0.0` we should feed back into https://github.com/nodejs/node/issues/25060

**Comment by ralphtheninja** [comment]
@Level/core I just released a premajor for `leveldown`. You can try it out with `npm i leveldown@5.0.0-0`.

**Comment by rvagg** [comment]
I didn't realise we'd been so long since the last release, and wow there are lot of commits.

If anyone else is interested here's the changelog so far (`changelog-maker --start-ref=v4.0.1`, also props to @ralphtheninja for so much of this work):

* [[`50a7d6f0c0`](https://github.com/level/leveldown/commit/50a7d6f0c0)] - Remove xcacheSize and xmaxOpenFiles from leak tests (#569) (Lars-Magnus Skog)
* [[`d73afd860e`](https://github.com/level/leveldown/commit/d73afd860e)] - 5.0.0-0 (Lars-Magnus Skog)
* [[`0c4b9783c8`](https://github.com/level/leveldown/commit/0c4b9783c8)] - Changelog and upgrade guide for v5.0.0-rc1 (#548) (Vincent Weevers)
* [[`0e88cdefcd`](https://github.com/level/leveldown/commit/0e88cdefcd)] - Remove node 6, use prebuildify fork for now, build on node 8 (#562) (Lars-Magnus Skog)
* [[`15536f9a7c`](https://github.com/level/leveldown/commit/15536f9a7c)] - Add publish instructions and download-prebuilds npm script (#564) (Vincent Weevers)
* [[`19118ce241`](https://github.com/level/leveldown/commit/19118ce241)] - mention electron in supported platforms (#563) (Vincent Weevers)
* [[`21080032e7`](https://github.com/level/leveldown/commit/21080032e7)] - Remove 32 bits from appveyor (#560) (Lars-Magnus Skog)
* [[`6c316a23d7`](https://github.com/level/leveldown/commit/6c316a23d7)] - Document new platform support and prebuilt binaries (#558) (Vincent Weevers)
* [[`1c30125280`](https://github.com/level/leveldown/commit/1c30125280)] - Document batch (array and chained form), sync option and db refs (#556) (Vincent Weevers)
* [[`eaa2b281e3`](https://github.com/level/leveldown/commit/eaa2b281e3)] - Set NAPI\_VERSION to 3 (#559) (Lars-Magnus Skog)
* [[`d08c48f91c`](https://github.com/level/leveldown/commit/d08c48f91c)] - Update minimum node version required (#552) (Lars-Magnus Skog)
* [[`45cab1cb07`](https://github.com/level/leveldown/commit/45cab1cb07)] - Use prebuildify (#549) (Lars-Magnus Skog)
* [[`c2fefcf4c0`](https://github.com/level/leveldown/commit/c2fefcf4c0)] - Merge pull request #540 from ralphtheninja/napi (Lars-Magnus Skog)
* [[`e80be43b9b`](https://github.com/level/leveldown/commit/e80be43b9b)] - Pass in leveldb::Slice into workers and not napi values (Lars-Magnus Skog)
* [[`d4dd7f047a`](https://github.com/level/leveldown/commit/d4dd7f047a)] - Tweak back if-statements to be more clear (Lars-Magnus Skog)
* [[`42da176853`](https://github.com/level/leveldown/commit/42da176853)] - Remove nan/v8 based glue code (Lars-Magnus Skog)
* [[`647c3dd77f`](https://github.com/level/leveldown/commit/647c3dd77f)] - Compress constructor arguments a little bit (Lars-Magnus Skog)
* [[`4bcffea3c8`](https://github.com/level/leveldown/commit/4bcffea3c8)] - Refactor some of the hideous iterator property code (Lars-Magnus Skog)
* [[`41c19a24ed`](https://github.com/level/leveldown/commit/41c19a24ed)] - Refactor calling code into CallFunction() (Lars-Magnus Skog)
* [[`cb34bf0ccb`](https://github.com/level/leveldown/commit/cb34bf0ccb)] - Use new instead of malloc to keep similar memory handling everywhere (Lars-Magnus Skog)
* [[`6aca8c8ba6`](https://github.com/level/leveldown/commit/6aca8c8ba6)] - Only need to set filterPolicy once when Database object is created (Lars-Magnus Skog)
* [[`885574974b`](https://github.com/level/leveldown/commit/885574974b)] - Dispose data pointed to by instances of leveldb::Slice (Lars-Magnus Skog)
* [[`d6001e1e05`](https://github.com/level/leveldown/commit/d6001e1e05)] - Fix some napi commands + clean up old comments and reduce some if-statements (Lars-Magnus Skog)
* [[`cb15d6e485`](https://github.com/level/leveldown/commit/cb15d6e485)] - Clean up debug printf (Lars-Magnus Skog)
* [[`02ccedab25`](https://github.com/level/leveldown/commit/02ccedab25)] - Reset back to normal testing (Lars-Magnus Skog)
* [[`1dfe434327`](https://github.com/level/leveldown/commit/1dfe434327)] - .destroy() now calls back with null (Lars-Magnus Skog)
* [[`50062ad5fd`](https://github.com/level/leveldown/commit/50062ad5fd)] - Accidentally disabled all tests but one :) (Lars-Magnus Skog)
* [[`ce049ddd47`](https://github.com/level/leveldown/commit/ce049ddd47)] - Implement db\_get\_property() (Lars-Magnus Skog)
* [[`a1f94dab84`](https://github.com/level/leveldown/commit/a1f94dab84)] - Implement repair\_db() (Lars-Magnus Skog)
* [[`ad079a561f`](https://github.com/level/leveldown/commit/ad079a561f)] - Implement destroy\_db() (Lars-Magnus Skog)
* [[`0790470692`](https://github.com/level/leveldown/commit/0790470692)] - Implement db\_compact\_range() (Lars-Magnus Skog)
* [[`fc46554f34`](https://github.com/level/leveldown/commit/fc46554f34)] - Fix "iterator has ended" error (Lars-Magnus Skog)
* [[`023deaee10`](https://github.com/level/leveldown/commit/023deaee10)] - Fix ending open iterators while closing database (+ reorder Iterator struct) (Lars-Magnus Skog)
* [[`8aba0c3eb4`](https://github.com/level/leveldown/commit/8aba0c3eb4)] - Implement dc\_approximate\_size() (Lars-Magnus Skog)
* [[`60b79828fd`](https://github.com/level/leveldown/commit/60b79828fd)] - Implement the rest of iterator\_seek() (Lars-Magnus Skog)
* [[`79966afcca`](https://github.com/level/leveldown/commit/79966afcca)] - Implement chained batch (+ rename some functions) (Lars-Magnus Skog)
* [[`52ccc82112`](https://github.com/level/leveldown/commit/52ccc82112)] - Implement batch\_do() for immediate write operation (Lars-Magnus Skog)
* [[`64ff8f6a7f`](https://github.com/level/leveldown/commit/64ff8f6a7f)] - Add TODO for db\_close() (when open iterators) (Lars-Magnus Skog)
* [[`f7c6d93238`](https://github.com/level/leveldown/commit/f7c6d93238)] - napi/leveldown.cc -\> binding.cc (Lars-Magnus Skog)
* [[`6f09aaf014`](https://github.com/level/leveldown/commit/6f09aaf014)] - Reorganize, macros at top, helpers etc (Lars-Magnus Skog)
* [[`8de66184eb`](https://github.com/level/leveldown/commit/8de66184eb)] - Implement db\_del() (Lars-Magnus Skog)
* [[`2acd4b6b54`](https://github.com/level/leveldown/commit/2acd4b6b54)] - Implement db\_get() (Lars-Magnus Skog)
* [[`5613fb5bdd`](https://github.com/level/leveldown/commit/5613fb5bdd)] - Fix error messages (needs to be copied) (Lars-Magnus Skog)
* [[`57b0be4bfc`](https://github.com/level/leveldown/commit/57b0be4bfc)] - Implement db\_close() (Lars-Magnus Skog)
* [[`043508a785`](https://github.com/level/leveldown/commit/043508a785)] - Implement iterator.next() and iterator.end() (Lars-Magnus Skog)
* [[`182a58bf72`](https://github.com/level/leveldown/commit/182a58bf72)] - Reuse LD\_STRING\_OR\_BUFFER\_TO\_COPY() macro in ToSlice() function (Lars-Magnus Skog)
* [[`6889722fb2`](https://github.com/level/leveldown/commit/6889722fb2)] - Implement iterator() (Lars-Magnus Skog)
* [[`20f2aea52d`](https://github.com/level/leveldown/commit/20f2aea52d)] - Move leveldb specific calls to Database (Lars-Magnus Skog)
* [[`3ede7b3d1c`](https://github.com/level/leveldown/commit/3ede7b3d1c)] - Lets adopt same naming as for nan case, DbContext -\> Database (Lars-Magnus Skog)
* [[`085ef08597`](https://github.com/level/leveldown/commit/085ef08597)] - Stub out iterator methods (Lars-Magnus Skog)
* [[`e37cda04f0`](https://github.com/level/leveldown/commit/e37cda04f0)] - Rename binding functions (Lars-Magnus Skog)
* [[`1fba29c962`](https://github.com/level/leveldown/commit/1fba29c962)] - Refactor common logic from OpenWorker and PutWorker into BaseWorker (Lars-Magnus Skog)
* [[`9f03290229`](https://github.com/level/leveldown/commit/9f03290229)] - Implement put() (not yet handling buffers) (Lars-Magnus Skog)
* [[`71e782349a`](https://github.com/level/leveldown/commit/71e782349a)] - Implement open() (Lars-Magnus Skog)
* [[`11797d8d17`](https://github.com/level/leveldown/commit/11797d8d17)] - Implement leveldown function (test/leveldown-test.js pass) (Lars-Magnus Skog)
* [[`0cf69aec5b`](https://github.com/level/leveldown/commit/0cf69aec5b)] - Bench tweaks (#546) (Lars-Magnus Skog)
* [[`b49194f482`](https://github.com/level/leveldown/commit/b49194f482)] - Update db-bench (#545) (Vincent Weevers)
* [[`d7b73d3e79`](https://github.com/level/leveldown/commit/d7b73d3e79)] - Merge pull request #539 from Level/normalize-gyp-files (Lars-Magnus Skog)
* [[`bc48b15e0d`](https://github.com/level/leveldown/commit/bc48b15e0d)] - Normalize gyp files (indentation and use " everywhere) (Lars-Magnus Skog)
* [[`a941d96f98`](https://github.com/level/leveldown/commit/a941d96f98)] - chore(package): update slump to version 3.0.0 (#504) (greenkeeper[bot])
* [[`c604cc443e`](https://github.com/level/leveldown/commit/c604cc443e)] - Serialize compact range options (#517) (Vincent Weevers)
* [[`cbb7459553`](https://github.com/level/leveldown/commit/cbb7459553)] - Fix snappy path in .npmignore (#535) (Philippe Schommers)
* [[`cdf0f1a2e8`](https://github.com/level/leveldown/commit/cdf0f1a2e8)] - Merge pull request #522 from filoozom/upgrade-snappy (Lars-Magnus Skog)
* [[`d41cc22395`](https://github.com/level/leveldown/commit/d41cc22395)] - Fix typo (Vincent Weevers)
* [[`98bf44998c`](https://github.com/level/leveldown/commit/98bf44998c)] - Add documentation about git submodules for developers (Philippe Schommers)
* [[`030825130a`](https://github.com/level/leveldown/commit/030825130a)] - Fix AppVeyor build (Philippe Schommers)
* [[`0ab9cf2658`](https://github.com/level/leveldown/commit/0ab9cf2658)] - Remove `git submodule update` (Philippe Schommers)
* [[`d8afaa5d10`](https://github.com/level/leveldown/commit/d8afaa5d10)] - Init submodules (Philippe Schommers)
* [[`baff261bd8`](https://github.com/level/leveldown/commit/baff261bd8)] - Move snappy to a git submodule (Philippe Schommers)
* [[`983ef6c299`](https://github.com/level/leveldown/commit/983ef6c299)] - Upgrade snappy to 1.1.7 (Philippe Schommers)
* [[`d72a533194`](https://github.com/level/leveldown/commit/d72a533194)] - Make callback of makeTest an error-first callback (#518) (Vincent Weevers)
* [[`a088f94c1e`](https://github.com/level/leveldown/commit/a088f94c1e)] - remove unused 'key' argument from ChainedBatch#\_clear (#519) (Vincent Weevers)
* [[`392394d687`](https://github.com/level/leveldown/commit/392394d687)] - Add segfault tests (#514) (Vincent Weevers)
* [[`d979b30888`](https://github.com/level/leveldown/commit/d979b30888)] - Merge pull request #511 from Level/finalize-next (Vincent Weevers)
* [[`1e1b1de2cb`](https://github.com/level/leveldown/commit/1e1b1de2cb)] - **readme**: value may not be null or undefined (Vincent Weevers)
* [[`9631b996d9`](https://github.com/level/leveldown/commit/9631b996d9)] - target abstract-leveldown@6 (Vincent Weevers)
* [[`922057ad8d`](https://github.com/level/leveldown/commit/922057ad8d)] - Merge pull request #508 from Level/next-migrate-seek-tests (Vincent Weevers)
* [[`1fb0e4f980`](https://github.com/level/leveldown/commit/1fb0e4f980)] - target Level/abstract-leveldown#b610da0 (Vincent Weevers)
* [[`87e83cc14d`](https://github.com/level/leveldown/commit/87e83cc14d)] - remove unused iota-array and lexicographic-integer devDependencies (Vincent Weevers)
* [[`23222b587d`](https://github.com/level/leveldown/commit/23222b587d)] - moved seek tests to abstract-leveldown (Vincent Weevers)
* [[`1fd0bdb9b4`](https://github.com/level/leveldown/commit/1fd0bdb9b4)] - Merge pull request #506 from Level/next-serialization2 (Vincent Weevers)
* [[`1e363aab8b`](https://github.com/level/leveldown/commit/1e363aab8b)] - implement \_serializeKey and \_serializeValue (Vincent Weevers)
* [[`82cdd77323`](https://github.com/level/leveldown/commit/82cdd77323)] - implement \_seek instead of seek (Vincent Weevers)
* [[`a007051f8a`](https://github.com/level/leveldown/commit/a007051f8a)] - target Level/abstract-leveldown#0f42686 (Vincent Weevers)
* [[`7b0f6d91c1`](https://github.com/level/leveldown/commit/7b0f6d91c1)] - Use suite.common() in test/common.js (Lars-Magnus Skog)
* [[`5745555a6e`](https://github.com/level/leveldown/commit/5745555a6e)] - Target abstract-leveldown#51af868 (Lars-Magnus Skog)
* [[`52b0777e9c`](https://github.com/level/leveldown/commit/52b0777e9c)] - Abstract tests single function (#495) (Lars-Magnus Skog)
* [[`e1ac18dbbc`](https://github.com/level/leveldown/commit/e1ac18dbbc)] - Location was removed from abstract-leveldown (#494) (Lars-Magnus Skog)
* [[`ab7c1a599d`](https://github.com/level/leveldown/commit/ab7c1a599d)] - Create next branch which targets master branch of abstract-leveldown (Lars-Magnus Skog)
* [[`0ccf1a27d1`](https://github.com/level/leveldown/commit/0ccf1a27d1)] - Merge pull request #503 from Level/greenkeeper/standard-12.0.0 (Lars-Magnus Skog)
* [[`7906d16886`](https://github.com/level/leveldown/commit/7906d16886)] - Fix standard (Lars-Magnus Skog)
* [[`6bffc43ae5`](https://github.com/level/leveldown/commit/6bffc43ae5)] - chore(package): update standard to version 12.0.0 (greenkeeper[bot])
* [[`55559b4bc9`](https://github.com/level/leveldown/commit/55559b4bc9)] - fix(package): update prebuild-install to version 5.0.0 (#490) (greenkeeper[bot])
* [[`7142cebc33`](https://github.com/level/leveldown/commit/7142cebc33)] - chore(package): update prebuild to version 8.0.0 (#502) (greenkeeper[bot])
* [[`627c7e33ab`](https://github.com/level/leveldown/commit/627c7e33ab)] - fix(package): update nan to version 2.11.0 (#501) (greenkeeper[bot])
* [[`819946c7ab`](https://github.com/level/leveldown/commit/819946c7ab)] - Add nyc and coveralls (#497) (Lars-Magnus Skog)
* [[`0f5f554e86`](https://github.com/level/leveldown/commit/0f5f554e86)] - Remove node 9 (Lars-Magnus Skog)
* [[`1d122b02b8`](https://github.com/level/leveldown/commit/1d122b02b8)] - Remove .jshintrc (Lars-Magnus Skog)
* [[`508027dcae`](https://github.com/level/leveldown/commit/508027dcae)] - Remove copyright headers from code (Lars-Magnus Skog)
* [[`8a29ecc714`](https://github.com/level/leveldown/commit/8a29ecc714)] - Remove contributors from package.json (Lars-Magnus Skog)
* [[`aea8613c6d`](https://github.com/level/leveldown/commit/aea8613c6d)] - Remove g++-4.8 apt package from Travis (#489) (Lars-Magnus Skog)
* [[`d04f233540`](https://github.com/level/leveldown/commit/d04f233540)] - Remove redundant db.close() from test/approximate-size-test.js (Lars-Magnus Skog)
* [[`f8077cf07d`](https://github.com/level/leveldown/commit/f8077cf07d)] - Tweak changelog (#483) (Lars-Magnus Skog)
* [[`98cbb4f733`](https://github.com/level/leveldown/commit/98cbb4f733)] - Tweak copyright years for less maintenance (Lars-Magnus Skog)

**Comment by ralphtheninja** [comment]
@rvagg Hi! Nice to see you around! :wave:

**Comment by vweevers** [comment]
Also see the [changelog](https://github.com/Level/leveldown/blob/master/CHANGELOG.md#unreleased) and [upgrade guide](https://github.com/Level/leveldown/blob/master/UPGRADING.md#v500-rc1) which summarize the above.

**Comment by vweevers** [comment]
@Level/core I released `level` [v5.0.0-0](https://github.com/Level/level/releases/tag/v5.0.0-0), containing the `leveldown` prerelease and `level-js` for browser support. You can try it out with `npm i level@next`. Makes it easier to test `leveldown` too. Happy new year!

**Comment by ralphtheninja** [comment]
@digitalinfinity No roadmap. We want to sort out cross compiled binaries first and it would be nice to get some testing done in related projects. I'm guessing we will release it soon ;)

**Comment by digitalinfinity** [comment]
Great news! Thanks for the quick reply!

**Comment by BridgeAR** [comment]
@ralphtheninja is there any release date in sight? Soon Node.js v12 will be released and older leveldown versions do not work with Node.js v12. It would be great if this could be resolved quickly, so we get clean [CITGM](https://github.com/nodejs/citgm) runs for before the official Node.js release.

**Comment by vweevers** [comment]
@BridgeAR There are some tasks that we'd _like_ to complete before v5 but no _musts_. Which is to say, we can decide to release end of this week - or the week after that if it works out with the node.js schedule, giving us a little bit more time (we don't have a lot of capacity atm).

**Comment by BridgeAR** [comment]
The official release date is April 23. We'll have release candidates once a week starting from next week on and we'll have a lot of CITGM runs. `leveldown` currently produces a lot of noise and I consider removing it for that reason until it's actually fixed.

It would therefore be great if the new version could be released as soon as possible.

**Comment by vweevers** [comment]
I hear you. I'll aim for friday (that's my open source day). Just can't make any promises.

**Comment by vweevers** [comment]
Done!
