### ISSUE TITLE
Doesn't support idb_cmp1 comparator

### ISSUE THREAD

**Issue by danger89** [Level/leveldown#679]
Hi,

When reading in a LevelDB Google database using your library I get an error:
`Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator"`

Meaning the database has a re implementation of the comparator. namely the idb_cmp1 one from Google/Chrome. Could you implement this comparator so we can read the LevelDB databases using your nice leveldown library. 

More info:
https://cs.chromium.org/chromium/src/content/browser/indexed_db/indexed_db_leveldb_operations.cc?type=cs&q=idb_cmp1&sq=package:chromium&g=0&l=43

Regards,
Melroy

**Comment by vweevers** [comment]
I suggest forking leveldown, see if you can make it work with Google's IndexedDB comparator. I reckon it'll be quite complicated, hooked into other parts of chromium, and because of that unlikely to be accepted here. Maybe leveldown can expose a way to override the default comparator - a PR for that would be welcome - so that the IndexedDB comparator can stay in userland.
