### ISSUE TITLE
Iterator#dispose

### ISSUE THREAD

**Issue by dominictarr** [Level/leveldown#7]
what sort of error can happen in `iterator.dispose(cb)`?

``` js
var i = db.iterator()

i.dispose(function (err) {
  //?  
})
```

if there is an error should I try disposing again? do I even care? I don't need the iterator any more,
so as long as it's gone now, that is all I need to know. Could `iterator.dispose()` take no callback?

**Comment by vweevers** [comment]
Closing because:

1. Though `leveldown` will not yield an error on end, `abstract-leveldown` can (if already ended).
2. On end, we `delete it` and release the snapshot (in that order), which matches recommended usage in LevelDB docs; there's no point to returning `it->status()`.
3. It's been established that it's important to `iterator.end()` in order to release resources. If you don't, the iterator may get garbage collected but this does _not_ release the snapshot. If you later close the database, `leveldown` will attempt to end the iterator, but segfault because the iterator was gc'ed. In addition, it is important to wait for the `iterator.end()` to complete. If you don't and attempt to `db.close()` you'll run into race issues. These things are true on master (N-API), 4.x and earlier versions.

#597 will improve the situation, by preventing GC of iterators until they are ended (either explicitly or on db close). It will be safe to forget calling `iterator.end()` or to not wait for it to complete - `db.close()` will take care of it. What will remain true however, is that if you don't end or close, you'll get a memory leak. I.e. we protect you from segfaults, but still recommend calling `iterator.end()`.
