### ISSUE TITLE
Multiple Assertion Failed !!

### ISSUE THREAD

**Issue by LRagji** [Level/leveldown#755]
I am using `node runtime 12.20.0 & 12.18.3` on a `Windows 10 & Mac 10.14.6` machine with following code, which is resulting in lot of Assertion Failed Messages:
```
var level = require('level-party')
var db = level(__dirname + '/data', { keyEncoding: 'binary', valueEncoding: 'json' })
const start = Buffer.allocUnsafe(8);
start.writeBigInt64BE(1n, 0);
const end = Buffer.allocUnsafe(8);
end.writeBigInt64BE(2n, 0);
let x = new Promise((a, r) => {
    db.createReadStream({ gte: start, lte: start })
        .on('data', function (data) {
            console.log(data.key, '=', data.value)
        })
        .on('error', function (err) {
            console.log('Oh my!', err)
            r();
        })
        .on('close', function () {
            console.log('Stream closed')
            a();
        })
        .on('end', function () {
            console.log('Stream ended')
            a();
        })
});
x.then((e) =>
    console.log("Done")
)
```
Message 1: Assertion Failed at binding.cc @ 545
Message 2:Assertion Failed at version_set.cc @ 798
![Message1](https://user-images.githubusercontent.com/22937426/106380772-65fc8380-63da-11eb-8dcf-5076143146f9.PNG)
![Message2](https://user-images.githubusercontent.com/22937426/106380773-672db080-63da-11eb-952e-44a4ad837c01.PNG)

**Comment by vweevers** [comment]
Does it still happen if you remove:

```js
.on('end', function () {
	console.log('Stream ended')
	a();
})
```

Because the `end` event, which means there's no more data to read, is fired before `close`, which means the underlying iterator was closed at which point it's safe to close the db or exit the process. If you resolve the promise on `end`, it's not yet safe to exit.

Since node 12, node calls finalizers on process exit and we've yet to implement a proper hook to account for this (see #667 and nodejs/node#28428). Without such a hook we hit the `_ended` assertion shown in your screenshot, which asserts that the db is properly closed before its resources are finalized.

**Comment by LRagji** [comment]
@vweevers as suggested ran by removing on "end" event still fails, additionally tried it on Mac as well with node 12.18.3 still fails with same assertions..

**Comment by vweevers** [comment]
That's not good. Does it also happen if you replace `var level = require('level-party')` with `var level = require('level')`?

**Comment by LRagji** [comment]
Ok this is interesting, using level package doesn't give this problem both are at 6.0.1 version...

**Comment by TanninOne** [comment]
I'm getting the same errors on Windows 10 with leveldown 5.6.0
Not sure if this helps but I get these when loading a leveldb that was previously written by leveldown 5.4.1.
I'm using two versions of my app, one using leveldown 5.4.1 the other 5.6.0 and the assertions only happen the first time running the newer version after I had run the older one.
After that if I stay on the newer version it doesn't occur, running the older version is ok but then going back to the new one causes the crash again.
It doesn't seem like any data gets lost in this.

In my system it happens during "createReadStream" but not right away, it seems to happen a random time after the stream was opened and a few items were generated.

Also I tried adding a delay before the call to createReadStream because I had a feeling it was a timing problem but that has the effect that the process dies silently instead of producing the assertion errors.

**Comment by TanninOne** [comment]
I've rebuild leveldown (5.6.0) so I get pdbs and debugged this a bit.
What I can say at this point is that on the C side FinalizeIterator gets called on an iterator for which no onEOFChunk (and thus Iterator.prototype._end from iterator.js) was called before, so the iterator gets garbage collected before the stream is done processing.

I can trigger the crash fairly reliable in my environment but I can't really say what'd be necessary to reproduce it, if I can provide any more information that would help I'd be happy to do so.

**Comment by LRagji** [comment]
Would this behavior be triggered when DB is empty? Say i said createstream for key range not existing? And for me why does level package work and not level-party is still a question 🤔
