### ISSUE TITLE
iteratorStream(db.iterator())

### ISSUE THREAD

**Issue by kingrupam** [Level/leveldown#775]
We have high traffic server, if Lots of User call ""iteratorStream(db.iterator())"" same time will it able to Provide data? 
will maxOpenFiles,cacheSize parameter help to solve this?

Will ""iteratorStream(db.iterator())"" use lots of cpu/ram or it will use minimal cpu/ram?

**Comment by malaxmimdkm** [comment]
Great question man, also I want to know this questions answers, I think first and last question is most important.

**Comment by vweevers** [comment]
> if Lots of User call ""iteratorStream(db.iterator())"" same time will it able to Provide data?

Yes, up to a point where you have too many active iterators, then you may see that performance goes down. It's best to benchmark it yourself, in the context of your application.

> will maxOpenFiles parameter help to solve this?

This will help with large data sets, rather than many readers.

> will cacheSize parameter help to solve this?

Possibly.

> Will ""iteratorStream(db.iterator())"" use lots of cpu/ram or it will use minimal cpu/ram?

It's a streaming interface, and in the case of `leveldown` it reads ahead by only 16 kb at a time, so memory usage will be low unless your individual keys or values are large. CPU usage should be minimal as well.

**Comment by kingrupam** [comment]
is it possible to increase 16 KB to 100kb or more at a time? 

```It's a streaming interface, and in the case of leveldown it reads ahead by only 16 kb at a time, so memory usage will be low unless your individual keys or values are large. CPU usage should be minimal as well.```

**Comment by vweevers** [comment]
Yes, through the undocumented `highWaterMark` option: `db.open({ highWaterMark: 100 * 1024 }, ...)` (https://github.com/Level/leveldown/issues/468).
