### ISSUE TITLE
Explanation of name in README? eg why is this called "leveldown"

### ISSUE THREAD

**Issue by rchrd2** [Level/leveldown#786]
As someone who is trying to understand the various pieces of this ecosystem, the naming of "level" "levelup" "leveldown" "level{insert string here}" are confusing. 

Is there a reason this is called "leveldown" instead of, like "level-db-node", or something more descriptive? What does the "down" mean here? 

Thank you.

**Comment by vweevers** [comment]
In short:

- `leveldown` is the lowest layer, providing storage
- `levelup` is the highest layer, providing safety and sugar like deferred open & promises
- `level` bundles them into a convenience package (along with `encoding-down` to provide encodings).

That's **`down + up = level`**. When in doubt, use `level`, it has what most folks need.

As for all the other names, some follow the `down + up = level` naming scheme too, for example `memdown + level = level-mem`. Others don't, simply because there's a lot of history here.
